### ISSUE TITLE
Enable automatic deploy

### ISSUE THREAD

**Issue by Solomonic** [crazyfactory/validation#3]
- setup up travis settings
- test if its workin when a git tag is set

**Comment by adhocore** [comment]
@turboatcrazyfactory you fixed it already right?

**Comment by peter279k** [comment]
It looks like the Travis CI build has been integrated.
I think this issue should be closed.

**Comment by turboatcrazyfactory** [comment]
@adhocore 	we still have a problem with gemfury integration. I'm not sure what the problem. But when running the commands in `deploy.sh` everything works fine. But when travis run `deploy.sh` does not work and get `remote service not enabled`.
![image](https://user-images.githubusercontent.com/26110220/48987107-7657aa80-f14e-11e8-86a0-112d16bc3dd2.png)

**Comment by adhocore** [comment]
must be due to gemfury quota?
